--Procedimientos
DROP PROCEDURE IF EXISTS SP_INSERTAR_INGRESO
DELIMITER $$
CREATE PROCEDURE SP_INSERTAR_INGRESO(
	IN P_DESCRIPCION VARCHAR(255),
    IN P_SEMANA DATE,
    IN P_CANTIDAD DECIMAL(10,2)
)
SP:BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	INSERT INTO `tbl_ingresos`(`DESCRIPCION`, `CANTIDAD`, `FECHA`) VALUES (P_DESCRIPCION,P_CANTIDAD,P_SEMANA);
	COMMIT;
END $$

DROP PROCEDURE IF EXISTS SP_INSERTAR_GASTO
DELIMITER $$
CREATE PROCEDURE SP_INSERTAR_GASTO(
	IN P_DESCRIPCION VARCHAR(255),
    IN P_SEMANA DATE,
    IN P_CANTIDAD DECIMAL(10,2)
)
SP:BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	INSERT INTO `tbl_gastos`(`DESCRIPCION`, `CANTIDAD`, `FECHA`) VALUES (P_DESCRIPCION,P_CANTIDAD,P_SEMANA);
	COMMIT;
END $$

DROP PROCEDURE IF EXISTS SP_INSERTAR_DEUDA
DELIMITER $$
CREATE PROCEDURE SP_INSERTAR_DEUDA(
	IN P_DESCRIPCION VARCHAR(255),
    IN P_FECHA DATE,
    IN P_CANTIDAD DECIMAL(10,2),
    IN P_CANT_PAGADA DECIMAL(10,2),
    IN P_ACREEDOR VARCHAR(255)
)
SP:BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	INSERT INTO `tbl_deudas`(`DESCRIPCION`, `CANTIDAD`, `ACREEDOR`, `CANT_PAGADA`, `FECHA`) 
		VALUES (P_DESCRIPCION, P_CANTIDAD, P_ACREEDOR, P_CANT_PAGADA, P_FECHA);
	COMMIT;
END $$


DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_INGRESO
DELIMITER $$
CREATE PROCEDURE SP_ACTUALIZAR_INGRESO(
	IN P_IDINGRESO INT,
	IN P_DESCRIPCION VARCHAR(255),
    IN P_SEMANA DATE,
    IN P_CANTIDAD DECIMAL(10,2)
)
SP:BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	UPDATE `tbl_ingresos` SET `DESCRIPCION`=P_DESCRIPCION,`CANTIDAD`=P_CANTIDAD,`FECHA`=P_SEMANA 
		WHERE ID_INGRESO = P_IDINGRESO;
	COMMIT;
END $$


DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_GASTO
DELIMITER $$
CREATE PROCEDURE SP_ACTUALIZAR_GASTO(
	IN P_ID_GASTO INT,
	IN P_DESCRIPCION VARCHAR(255),
    IN P_SEMANA DATE,
    IN P_CANTIDAD DECIMAL(10,2)
)
SP: BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	UPDATE `tbl_gastos` SET `DESCRIPCION`=P_DESCRIPCION,`CANTIDAD`=P_CANTIDAD,`FECHA`=P_SEMANA 
		WHERE ID_GASTO = P_ID_GASTO;
	COMMIT;
END $$


DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_DEUDA
DELIMITER $$
CREATE PROCEDURE SP_ACTUALIZAR_DEUDA(
	IN P_ID_DEUDA INT,
	IN P_DESCRIPCION VARCHAR(255),
    IN P_FECHA DATE,
    IN P_CANTIDAD DECIMAL(10,2),
    IN P_CANT_PAGADA DECIMAL(10,2),
    IN P_ACREEDOR VARCHAR(255)
)
SP: BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	UPDATE `tbl_deudas` SET `DESCRIPCION`=P_DESCRIPCION,`CANTIDAD`=P_CANTIDAD,`ACREEDOR`=P_ACREEDOR,`CANT_PAGADA`=P_CANT_PAGADA ,`FECHA`= P_FECHA
		WHERE ID_DEUDA = P_ID_DEUDA;
COMMIT;
END $$

DROP PROCEDURE IF EXISTS SP_ELIMINAR_INGRESO
DELIMITER $$
CREATE PROCEDURE SP_ELIMINAR_INGRESO(
	IN P_IDINGRESO INT
)
SP:BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	DELETE FROM `tbl_ingresos` WHERE ID_INGRESO = P_IDINGRESO;
	COMMIT;
END $$

DROP PROCEDURE IF EXISTS SP_ELIMINAR_GASTO
DELIMITER $$
CREATE PROCEDURE SP_ELIMINAR_GASTO(
	IN P_IDGASTO INT
)
SP:BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	DELETE FROM `tbl_gastos` WHERE ID_GASTO = P_IDGASTO;
	COMMIT;
END $$

DROP PROCEDURE IF EXISTS SP_ELIMINAR_DEUDA
DELIMITER $$
CREATE PROCEDURE SP_ELIMINAR_DEUDA(
	IN P_IDDEUDA INT
)
SP:BEGIN
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	DELETE FROM `tbl_gastos` WHERE ID_DEUDA = P_IDDEUDA;
	COMMIT;
END $$

DROP PROCEDURE IF EXISTS SP_INGRESOS_MES
DELIMITER $$
CREATE PROCEDURE SP_INGRESOS_MES(
	IN P_ANIO INT,
	IN P_MES INT
)
BEGIN  
   SELECT * from tbl_ingresos where MONTH(FECHA) = P_MES AND YEAR(fecha) = P_ANIO; 
END $$
